### ISSUE TITLE
Construção do questionário para entrevista

### ISSUE THREAD

**Issue by ricardopoppi** [transformagov/transformagov#19]
Para ser realizado em janeiro

**Comment by parrahenri** [comment]
Pensei em termos 2 blocos de perguntas.

1) uso em função da organização
Para quais atividades você utiliza o software transforma? 
Em que organização você trabalha? [Descreva brevemente o negócio dela]
Quais funções você desempenha nessa organização?
Há quanto tempo você utiliza o transforma?
Quantas pessoas na sua organização utilizam o transforma?
Pode me indicar o nome de três pessoas que utilizam o transforma em sua organização?

2) comunidades
Como você conheceu o software Transforma?
Sabe quem desenvolveu/ criou ele?
Você já participou de algum processo de melhoria ou mudança do software? [relatando problemas, demandando novas funcionalidades etc]
Descreva em detalhes caso sua resposta ao item anterior seja sim.

Me digam se falta algum item, se não vou lapidando esses @ricardopoppi @davidCarlos

**Comment by parrahenri** [comment]
Temos muitos ou poucos atores pra entrevistar?
Porque podemos pensar um terceiro bloco mais aprofundado em termos de comunidade para alguns atores-chave, sabe?  Esses dois blocos seria um questionário padrão e podemos adicionar perguntas detalhadas para aqueles que a gente sabe que tê papel de governança (seja na camada de negócio, seja na camada de programação)

**Comment by ricardopoppi** [comment]
@parrahenri os blocos estão ótimos. minhas sugestões:

No bloco 1 eu incluiria tb uma pergunta sobre resultados e uma irreverente sobre como vender o transforma:
- Já foi possível obter algum resultado da utilização do software? Quais forma os mais marcantes?
- Se você tivesse que convencer alguém a utilizar o transforma na sua organização, como seria o seu "pitch de venda"?

E também sugiro um bloco focado nos desenvolvedores e nos evangelizadores. Aí no questinário a primeira pergunta que a gente faz é se a pessoa é desenvolvedora do software ou usuário ou evangelizador não usuário (pode ter esse perfil na comunidade)

Desenvolvedores:
Por quanto tempo que vc trabalha desenvolvendo o transforma?
Qual o seu papel no desenvolvimento do software?
Para qual organização você trabalha?
Quantos desenvolvedores trabalham desenvolvendo o transforma na sua organização?
Você tem relação com os usuários do software? Qual a frequência?
Você tem contato com pessoas de outras organizações que trabalham na divulgação do transforma? Quais?

Evangelizadores
Por quanto tempo que vc trabalha na divulgação e apoio ao Transforma?
Qual o principal motivo de sua organização apoiar o software?
Quantas pessoas da sua organização trabalham em alguma atividade ligada ao software
(aí um espaço pra pessoa marcar um número na frente de: promoção / divulgação / financiamento / testes / desenvolvimento) 
Você já chegou a sugerir alguma melhoria para o software? Se sim, faz isso com que frequência?

**Comment by parrahenri** [comment]
Apenas sistematizando:

uso em função da organização
Para quais atividades você utiliza o software transforma?
Em que organização você trabalha? [Descreva brevemente o negócio dela]
Quais funções você desempenha nessa organização?
Há quanto tempo você utiliza o transforma?
Quantas pessoas na sua organização utilizam o transforma?
Pode me indicar o nome de três pessoas que utilizam o transforma em sua organização?
Já foi possível obter algum resultado da utilização do software? Quais forma os mais marcantes?
Se você tivesse que convencer alguém a utilizar o transforma na sua organização, como seria o seu "pitch de venda"?

comunidades
Como você conheceu o software Transforma?
Sabe quem desenvolveu/ criou ele?
Você já participou de algum processo de melhoria ou mudança do software? [relatando problemas, demandando novas funcionalidades etc]
Descreva em detalhes caso sua resposta ao item anterior seja sim.

Desenvolvedores:
Por quanto tempo que vc trabalha desenvolvendo o transforma?
Qual o seu papel no desenvolvimento do software?
Para qual organização você trabalha?
Quantos desenvolvedores trabalham desenvolvendo o transforma na sua organização?
Você tem relação com os usuários do software? Qual a frequência?
Você tem contato com pessoas de outras organizações que trabalham na divulgação do transforma? Quais?

Evangelizadores
Por quanto tempo que vc trabalha na divulgação e apoio ao Transforma?
Qual o principal motivo de sua organização apoiar o software?
Quantas pessoas da sua organização trabalham em alguma atividade ligada ao software
(aí um espaço pra pessoa marcar um número na frente de: promoção / divulgação / financiamento / testes / desenvolvimento)
Você já chegou a sugerir alguma melhoria para o software? Se sim, faz isso com que frequência?

**Comment by ricardopoppi** [comment]
@parrahenri ótimo! acho que já estamos prontos pras entrevistas!

**Comment by parrahenri** [comment]
Pra testarem o formulário que será usado nas entrevistas: https://forms.gle/AK6pjBEGUviNVDKV7
