### ISSUE TITLE
Preparar a mensagem para envio a contatos da Fundação Lemann e SEPLAG/MG

### ISSUE THREAD

**Issue by ricardopoppi** [transformagov/transformagov#21]
Uma mensagem que consiga captar rapidamente algumas informações básicas sobre o transforma

**Comment by ricardopoppi** [comment]
Prezado <nome-da-pessoa>, como você está?

Na semana passada nós começamos a organizar nosso trabalho da frente de comunidade do projeto Transforma! Estamos empolgados! Em janeiro vamos te convidar para uma entrevista rápida que nos ajudará a produzir os conteúdos da landing page do software o mais alinhado possível com a visão dos principais contribuidores do transforma.

Antes do recesso de final de ano, gostaríamos de te pedir um apoio pontual, se for possível. Responder de forma livre a pergunta abaixo, respondendo essa mensagem mesmo:

Quem utiliza o transforma hoje e para que ele é usado? Pode me indicar o nome e instituição de mais 3 pessoas que trabalham de alguma forma como transforma?

Muito obrigado, qualquer dúvida estamos a disposição.

**Comment by ricardopoppi** [comment]
@davidCarlos esse é o conteúdo do email, sugiro mandarmos para 1-2 pessoas da seplag/mg e 1-2 pessoas da lemann. Nesse momento o que vier é lucro, já que a entrevista mais estruturada vamos aplicar em janeiro

**Comment by davidCarlos** [comment]
> @davidCarlos esse é o conteúdo do email, sugiro mandarmos para 1-2 pessoas da seplag/mg e 1-2 pessoas da lemann. Nesse momento o que vier é lucro, já que a entrevista mais estruturada vamos aplicar em janeiro

show, de acordo.
