### ISSUE TITLE
Coleta de informações preliminares por email

### ISSUE THREAD

**Issue by ricardopoppi** [transformagov/transformagov#23]
Emails enviados com uma pergunta:

**Quem utiliza o Transforma hoje e para que ele é usado? Pode me indicar o nome e instituição de mais 3 pessoas que trabalham de alguma forma como Transforma?**

**Comment by ricardopoppi** [comment]
**Primeira resposta**

O Sistema Transforma Minas foi concebido para operacionalizar a frente de seleção do Programa Transforma Minas cujo objetivo é recrutar profissionais altamente capacitados para cargos de alta gestão no estado de Minas Gerais, por meio de uma metodologia criada em conjunto com instituições parceiras que estabelece critérios mais objetivos e meritocráticos para os processos de seleção. 

Nesse sentido, o sistema permite à equipe central do Programa cadastrar comissões de avaliação e todo o processo de avaliação, desde a criação das questões a serem respondidas pelos candidatos em cada etapa ao agendamento de entrevistas e avaliação das candidaturas recebidas. Ao candidato, é possível criar um perfil com informações básicas de currículo e se candidatar a qualquer vaga disponibilizada percorrendo as etapas de avaliação previstas pelo Programa.

Desde o início de sua implementação o Sistema Transforma Minas executou com sucesso 37 vagas do Programa, com cerca de 3.579 candidaturas registradas e mais de 4.647 candidatos cadastrados na plataforma. Ao todo, registramos vagas referentes a 8 órgãos, sendo a grande maioria delas destinadas à Controladoria Geral do Estado (CGE) com 23 processos distintos realizados no sistema.  

Vale destacar, por fim, que a abertura do código em repositório público permite a outros entes utilizarem o sistema para processos seletivos semelhantes à metodologia utilizada pelo Programa.

**Comment by ricardopoppi** [comment]
**Segunda resposta**

O sistema é utilizado por várias instituições do Governo do Estado de Minas Gerais e pelos candidatos a cargos de chefia. Nossa equipe que é responsável pela manutenção do sistema não tem contato com os usuários da ponta, somente com a equipe de negócio responsável pelo programa. Quem interage diretamente com essa equipe é o Giuliano da minha equipe (em cópia). Talvez seja mais interessante entrar em contato com ele. Eu só conheço a Luciana Custódio aqui da SEPLAG que é a coordenadora do programa.

**Comment by ricardopoppi** [comment]
@parrahenri @davidCarlos recebi duas respostas, reproduzi nos comentários acima

**Comment by parrahenri** [comment]
> @parrahenri @davidCarlos recebi duas respostas, reproduzi nos comentários acima

Gostei dessas 2 primeiras respostas! Mas percebi que a "bola de neve" não cresceu. 2 pessoas e apenas + 1 indicada. Acho que a última pergunta precisa ser explícita:

Indique pelo menos 3 nomes de pessoas....

Que acham?

**Comment by ricardopoppi** [comment]
boa, como entramos na fase das entrevistas estou fechando essa e deixamos essa pergunta bem explícita no roteiro
